[project]
name = "pyaudiocontroller"
version = "0.1.0"
description = "pyaudiocontroller"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "GPL-3.0" }
dependencies = [
    "numpy",
    "pyaudio",
    "pynput",
    "sounddevice>=0.5.1",
]


