[project]
name = "pyaudiocontroller"
version = "0.1.0"
description = "pyaudiocontroller"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aubio",
    "numpy",
    "pyaudio",
    "pynput",
]
